name: yuricable.pro
on: push
jobs:
   # Build and Deploy Job
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Code
           uses: actions/checkout@v3
         - name: Install Node
           uses: actions/setup-node@v3
           with:
              node-version: 18.x
         - name: Install Dependencies
           run: npm install
         - name: Build Project
           run: npm run build
         - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.TOKEN }}
             publish_dir: ./build
             publish_branch: gh-pages
   # Deploy Job
   #deploy:
   #   needs: build
   #   runs-on: ubuntu-latest
   #   steps:
   #      - name: Download artifact
   #        uses: actions/download-artifact@v4
   #        with:
   #           name: yuricablesite
   #           run-id: ${{ github.event.workflow_run.id }}
    ##          path: ./build
    #     - name: Deploy to GitHub Pages
    #       uses: peaceiris/actions-gh-pages@v3
     ##      with:
     #         github_token: ${{ secrets.CI_CD_TOKEN }}
     #         publish_dir: ./build
